# This file was generated by GoReleaser. DO NOT EDIT.
cask "kuality" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/kuality-io/cli/releases/download/v#{version}/kuality_#{version}_darwin_amd64.tar.gz"
      sha256 "e20a3bcdd7b5a963588bcf00fcfc322d69189a1c2353824ff903ca789d31e33a"
    end
    on_arm do
      url "https://github.com/kuality-io/cli/releases/download/v#{version}/kuality_#{version}_darwin_arm64.tar.gz"
      sha256 "b2304dfd2d02dbed8d11457277fe2ac3f7b4125bbe5601b0cae250ceeed0a58c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kuality-io/cli/releases/download/v#{version}/kuality_#{version}_linux_amd64.tar.gz"
      sha256 "b7e6481bb1cb2a8a2891c4ccdfe2239c93e04554090be9cfbb210e8ee9019c99"
    end
    on_arm do
      url "https://github.com/kuality-io/cli/releases/download/v#{version}/kuality_#{version}_linux_arm64.tar.gz"
      sha256 "1e22ae98081673996b962d19c57d4be86fe19f6925bb4e1a5d3d33cc3cf12c1a"
    end
  end

  name "kuality"
  desc "Scan any website for accessibility, performance, SEO, cross-browser, and 30+ QA dimensions"
  homepage "https://kuality.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kuality"

  # No zap stanza required

end
